version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY: "lightsail/astro-app-ssh-key"
  variables:
    LIGHTSAIL_INSTANCE_NAME: "astro-example-company-website"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Fetching Lightsail instance IP..."
      - export DEPLOY_HOST=$(aws lightsail get-instance --instance-name $LIGHTSAIL_INSTANCE_NAME --region $AWS_REGION --query 'instance.publicIpAddress' --output text)
      - echo "Deploy target: $DEPLOY_HOST"
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
      - chmod 600 ~/.ssh/deploy_key
      - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null

  build:
    commands:
      - echo "Creating deployment package..."
      - tar -czf /tmp/deploy.tar.gz --exclude='node_modules' --exclude='.git' --exclude='dist' .
      - echo "Package created successfully"

  post_build:
    commands:
      - export DEPLOY_HOST=$(aws lightsail get-instance --instance-name $LIGHTSAIL_INSTANCE_NAME --region $AWS_REGION --query 'instance.publicIpAddress' --output text)
      - echo "Deploying to Lightsail instance $LIGHTSAIL_INSTANCE_NAME ($DEPLOY_HOST)..."
      # Copy deployment package to server
      - scp -i ~/.ssh/deploy_key /tmp/deploy.tar.gz bitnami@$DEPLOY_HOST:/tmp/
      # Deploy on server
      - |
        ssh -i ~/.ssh/deploy_key bitnami@$DEPLOY_HOST 'bash -s' << 'DEPLOY'
        set -e
        cd ~/app
        # Extract new version
        tar -xzf /tmp/deploy.tar.gz
        # Install dependencies
        npm ci
        # Build
        npm run build
        # Restart the application
        pm2 restart astro-app
        # Clean up
        rm /tmp/deploy.tar.gz
        echo "Deployment complete!"
        DEPLOY
      - echo "Deployment successful!"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*

