version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY: "lightsail/astro-app-ssh-key"
  variables:
    LIGHTSAIL_INSTANCE_NAME: "astro-example-company-website"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Fetching Lightsail instance IP..."
      - DEPLOY_HOST=$(aws lightsail get-instance --instance-name $LIGHTSAIL_INSTANCE_NAME --region $AWS_REGION --query "instance.publicIpAddress" --output text)
      - echo "Deploy target is $DEPLOY_HOST"
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
      - chmod 600 ~/.ssh/deploy_key
      - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null
      - echo "DEPLOY_HOST=$DEPLOY_HOST" >> $CODEBUILD_SRC_DIR/env.txt

  build:
    commands:
      - echo "Creating deployment package..."
      - tar -czf /tmp/deploy.tar.gz --exclude=node_modules --exclude=.git --exclude=dist .
      - echo "Package created successfully"

  post_build:
    commands:
      - source $CODEBUILD_SRC_DIR/env.txt
      - echo "Deploying to $DEPLOY_HOST..."
      - scp -i ~/.ssh/deploy_key /tmp/deploy.tar.gz bitnami@$DEPLOY_HOST:/tmp/
      - ssh -i ~/.ssh/deploy_key bitnami@$DEPLOY_HOST "cd ~/app && tar -xzf /tmp/deploy.tar.gz && npm ci && npm run build && pm2 restart astro-app && rm /tmp/deploy.tar.gz && echo Done"
      - echo "Deployment successful!"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**/*

